"""Ed25519 license signature verification.

The **public key** is embedded as a constant so that once compiled to a
``.so`` via Nuitka, customers cannot swap it out to forge licenses.

All heavy cryptographic work is delegated to the ``cryptography`` library
which is already a project dependency (via ``python-jose[cryptography]``).
"""

from __future__ import annotations

import base64
import json
import logging
from pathlib import Path

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey

from app.licensing.schema import LicenseFile, LicensePayload

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Embedded Ed25519 public key (base64-encoded, 32 bytes raw).
#
# Replace this placeholder with the real key generated by
#   tools/license_gen.py generate-keypair
#
# Once compiled into a .so file via Nuitka, this value is opaque to customers.
# ---------------------------------------------------------------------------
_PUBLIC_KEY_B64 = "REPLACE_WITH_REAL_PUBLIC_KEY_BASE64"

_SEPARATOR = "\n---\n"


def _get_public_key() -> Ed25519PublicKey:
    """Deserialise the embedded public key bytes into a verifier."""
    raw = base64.b64decode(_PUBLIC_KEY_B64)
    return Ed25519PublicKey.from_public_bytes(raw)


def load_license_file(path: str | Path) -> LicenseFile:
    """Parse a ``.lic`` file into its payload + signature components.

    The file format is::

        <base64-encoded JSON payload>
        ---
        <base64-encoded Ed25519 signature>

    Raises ``ValueError`` on malformed files.
    """
    text = Path(path).read_text(encoding="utf-8").strip()
    if _SEPARATOR not in text:
        raise ValueError("License file missing separator (---)")

    payload_b64, sig_b64 = text.split(_SEPARATOR, maxsplit=1)
    payload_bytes = base64.b64decode(payload_b64)
    signature = base64.b64decode(sig_b64)

    payload_dict = json.loads(payload_bytes)
    payload = LicensePayload.model_validate(payload_dict)

    return LicenseFile(
        payload=payload,
        payload_bytes=payload_bytes,
        signature=signature,
    )


def verify_signature(license_file: LicenseFile) -> bool:
    """Verify the Ed25519 signature of the license payload.

    Returns ``True`` if valid, ``False`` if the signature does not match.
    """
    try:
        pub = _get_public_key()
        pub.verify(license_file.signature, license_file.payload_bytes)
        return True
    except InvalidSignature:
        logger.warning("License signature verification FAILED")
        return False
    except (ValueError, TypeError) as exc:
        logger.error("Cannot load public key for verification: %s", exc)
        return False
