"""Add review tracking fields to payroll.salary_slip.

Revision ID: 20260131_add_salary_slip_review_fields
Revises: 20260131_add_payroll_entry_bank_account
Create Date: 2026-01-31
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "20260131_add_salary_slip_review_fields"
down_revision = "20260131_add_payroll_entry_bank_account"
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if not inspector.has_table("salary_slip", schema="payroll"):
        return

    columns = {
        col["name"] for col in inspector.get_columns("salary_slip", schema="payroll")
    }

    if "is_auto_generated" not in columns:
        op.add_column(
            "salary_slip",
            sa.Column(
                "is_auto_generated",
                sa.Boolean(),
                nullable=False,
                server_default="false",
                comment="Whether this slip was auto-generated by scheduled task",
            ),
            schema="payroll",
        )

    if "needs_review" not in columns:
        op.add_column(
            "salary_slip",
            sa.Column(
                "needs_review",
                sa.Boolean(),
                nullable=False,
                server_default="false",
                comment="Flag for slips requiring manual review before approval",
            ),
            schema="payroll",
        )

    if "review_reasons" not in columns:
        op.add_column(
            "salary_slip",
            sa.Column(
                "review_reasons",
                postgresql.JSONB,
                nullable=True,
                comment="List of reasons why review is needed (e.g., attendance gaps, proration)",
            ),
            schema="payroll",
        )

    if "reviewed_at" not in columns:
        op.add_column(
            "salary_slip",
            sa.Column(
                "reviewed_at",
                sa.DateTime(),
                nullable=True,
                comment="When the slip was reviewed/acknowledged",
            ),
            schema="payroll",
        )

    if "reviewed_by_id" not in columns:
        op.add_column(
            "salary_slip",
            sa.Column(
                "reviewed_by_id",
                postgresql.UUID(as_uuid=True),
                nullable=True,
                comment="Who reviewed/acknowledged the slip",
            ),
            schema="payroll",
        )

    fks = {
        fk.get("name")
        for fk in inspector.get_foreign_keys("salary_slip", schema="payroll")
    }
    if "fk_salary_slip_reviewed_by" not in fks:
        op.create_foreign_key(
            "fk_salary_slip_reviewed_by",
            "salary_slip",
            "people",
            ["reviewed_by_id"],
            ["id"],
            source_schema="payroll",
        )


def downgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if not inspector.has_table("salary_slip", schema="payroll"):
        return

    columns = {
        col["name"] for col in inspector.get_columns("salary_slip", schema="payroll")
    }
    fks = {
        fk.get("name")
        for fk in inspector.get_foreign_keys("salary_slip", schema="payroll")
    }

    if "fk_salary_slip_reviewed_by" in fks:
        op.drop_constraint(
            "fk_salary_slip_reviewed_by",
            "salary_slip",
            schema="payroll",
            type_="foreignkey",
        )

    if "reviewed_by_id" in columns:
        op.drop_column("salary_slip", "reviewed_by_id", schema="payroll")
    if "reviewed_at" in columns:
        op.drop_column("salary_slip", "reviewed_at", schema="payroll")
    if "review_reasons" in columns:
        op.drop_column("salary_slip", "review_reasons", schema="payroll")
    if "needs_review" in columns:
        op.drop_column("salary_slip", "needs_review", schema="payroll")
    if "is_auto_generated" in columns:
        op.drop_column("salary_slip", "is_auto_generated", schema="payroll")
