"""Add tax schema tables.

Revision ID: add_tax_schema_tables
Revises: add_banking_schema
Create Date: 2025-02-04
"""

from alembic import op
from app.alembic_utils import ensure_enum

# revision identifiers, used by Alembic.
revision = "add_tax_schema_tables"
down_revision = "add_banking_schema"
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    ensure_enum(
        bind,
        "difference_type",
        "TEMPORARY_TAXABLE",
        "TEMPORARY_DEDUCTIBLE",
        "PERMANENT",
    )
    ensure_enum(bind, "tax_period_frequency", "MONTHLY", "QUARTERLY", "ANNUAL")
    ensure_enum(bind, "tax_period_status", "OPEN", "FILED", "PAID", "CLOSED")
    ensure_enum(
        bind,
        "tax_return_status",
        "DRAFT",
        "PREPARED",
        "REVIEWED",
        "FILED",
        "AMENDED",
    )
    ensure_enum(bind, "tax_return_type", "VAT", "GST", "SALES_TAX", "WITHHOLDING", "INCOME", "PAYROLL")
    ensure_enum(
        bind,
        "tax_transaction_type",
        "INPUT",
        "OUTPUT",
        "WITHHOLDING",
        "ACCRUAL",
        "PAYMENT",
        "REFUND",
    )
    ensure_enum(
        bind,
        "tax_type",
        "VAT",
        "GST",
        "SALES_TAX",
        "WITHHOLDING",
        "INCOME_TAX",
        "EXCISE",
        "CUSTOMS",
        "OTHER",
    )

    statements = [
        """CREATE SCHEMA IF NOT EXISTS tax;""",
        """CREATE TABLE IF NOT EXISTS tax.tax_jurisdiction (
	jurisdiction_id UUID DEFAULT gen_random_uuid() NOT NULL, 
	organization_id UUID NOT NULL, 
	jurisdiction_code VARCHAR(30) NOT NULL, 
	jurisdiction_name VARCHAR(200) NOT NULL, 
	description TEXT, 
	country_code VARCHAR(3) NOT NULL, 
	state_province VARCHAR(100), 
	jurisdiction_level VARCHAR(30) NOT NULL, 
	current_tax_rate NUMERIC(10, 6) NOT NULL, 
	tax_rate_effective_from DATE NOT NULL, 
	future_tax_rate NUMERIC(10, 6), 
	future_rate_effective_from DATE, 
	has_reduced_rate BOOLEAN NOT NULL, 
	reduced_rate NUMERIC(10, 6), 
	reduced_rate_threshold NUMERIC(20, 6), 
	fiscal_year_end_month NUMERIC(2, 0) NOT NULL, 
	filing_due_months NUMERIC(2, 0) NOT NULL, 
	extension_months NUMERIC(2, 0), 
	currency_code VARCHAR(3) NOT NULL, 
	tax_authority_name VARCHAR(200), 
	tax_id_number VARCHAR(50), 
	current_tax_payable_account_id UUID NOT NULL, 
	current_tax_expense_account_id UUID NOT NULL, 
	deferred_tax_asset_account_id UUID NOT NULL, 
	deferred_tax_liability_account_id UUID NOT NULL, 
	deferred_tax_expense_account_id UUID NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (jurisdiction_id), 
	CONSTRAINT uq_tax_jurisdiction UNIQUE (organization_id, jurisdiction_code), 
	FOREIGN KEY(organization_id) REFERENCES core_org.organization (organization_id)
);""",
        """CREATE TABLE IF NOT EXISTS tax.deferred_tax_basis (
	basis_id UUID DEFAULT gen_random_uuid() NOT NULL, 
	organization_id UUID NOT NULL, 
	jurisdiction_id UUID NOT NULL, 
	basis_code VARCHAR(50) NOT NULL, 
	basis_name VARCHAR(200) NOT NULL, 
	description TEXT, 
	difference_type difference_type NOT NULL, 
	source_type VARCHAR(50) NOT NULL, 
	source_id UUID, 
	gl_account_id UUID, 
	accounting_base NUMERIC(20, 6) NOT NULL, 
	tax_base NUMERIC(20, 6) NOT NULL, 
	temporary_difference NUMERIC(20, 6) NOT NULL, 
	applicable_tax_rate NUMERIC(10, 6) NOT NULL, 
	deferred_tax_amount NUMERIC(20, 6) NOT NULL, 
	is_asset BOOLEAN NOT NULL, 
	is_recognized BOOLEAN NOT NULL, 
	recognition_probability NUMERIC(5, 4), 
	unrecognized_amount NUMERIC(20, 6) NOT NULL, 
	expected_reversal_year NUMERIC(4, 0), 
	is_current_year_reversal BOOLEAN NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (basis_id), 
	CONSTRAINT uq_deferred_tax_basis UNIQUE (organization_id, basis_code), 
	FOREIGN KEY(organization_id) REFERENCES core_org.organization (organization_id), 
	FOREIGN KEY(jurisdiction_id) REFERENCES tax.tax_jurisdiction (jurisdiction_id)
);""",
        """CREATE TABLE IF NOT EXISTS tax.tax_code (
	tax_code_id UUID DEFAULT gen_random_uuid() NOT NULL, 
	organization_id UUID NOT NULL, 
	tax_code VARCHAR(30) NOT NULL, 
	tax_name VARCHAR(100) NOT NULL, 
	description TEXT, 
	tax_type tax_type NOT NULL, 
	jurisdiction_id UUID NOT NULL, 
	tax_rate NUMERIC(10, 6) NOT NULL, 
	effective_from DATE NOT NULL, 
	effective_to DATE, 
	is_compound BOOLEAN NOT NULL, 
	is_inclusive BOOLEAN NOT NULL, 
	is_recoverable BOOLEAN NOT NULL, 
	recovery_rate NUMERIC(5, 4) NOT NULL, 
	applies_to_purchases BOOLEAN NOT NULL, 
	applies_to_sales BOOLEAN NOT NULL, 
	tax_return_box VARCHAR(30), 
	reporting_code VARCHAR(30), 
	tax_collected_account_id UUID, 
	tax_paid_account_id UUID, 
	tax_expense_account_id UUID, 
	is_active BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (tax_code_id), 
	CONSTRAINT uq_tax_code UNIQUE (organization_id, tax_code), 
	FOREIGN KEY(organization_id) REFERENCES core_org.organization (organization_id), 
	FOREIGN KEY(jurisdiction_id) REFERENCES tax.tax_jurisdiction (jurisdiction_id)
);""",
        """CREATE TABLE IF NOT EXISTS tax.tax_period (
	period_id UUID DEFAULT gen_random_uuid() NOT NULL, 
	organization_id UUID NOT NULL, 
	jurisdiction_id UUID NOT NULL, 
	fiscal_period_id UUID, 
	period_name VARCHAR(30) NOT NULL, 
	frequency tax_period_frequency NOT NULL, 
	start_date DATE NOT NULL, 
	end_date DATE NOT NULL, 
	due_date DATE NOT NULL, 
	status tax_period_status NOT NULL, 
	is_extension_filed BOOLEAN NOT NULL, 
	extended_due_date DATE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (period_id), 
	CONSTRAINT uq_tax_period UNIQUE (organization_id, jurisdiction_id, period_name), 
	FOREIGN KEY(organization_id) REFERENCES core_org.organization (organization_id), 
	FOREIGN KEY(jurisdiction_id) REFERENCES tax.tax_jurisdiction (jurisdiction_id)
);""",
        """CREATE INDEX IF NOT EXISTS idx_tax_period_dates ON tax.tax_period (start_date, end_date);""",
        """CREATE TABLE IF NOT EXISTS tax.tax_reconciliation (
	reconciliation_id UUID DEFAULT gen_random_uuid() NOT NULL, 
	organization_id UUID NOT NULL, 
	fiscal_period_id UUID NOT NULL, 
	jurisdiction_id UUID NOT NULL, 
	profit_before_tax NUMERIC(20, 6) NOT NULL, 
	statutory_tax_rate NUMERIC(10, 6) NOT NULL, 
	tax_at_statutory_rate NUMERIC(20, 6) NOT NULL, 
	permanent_differences NUMERIC(20, 6) NOT NULL, 
	non_deductible_expenses NUMERIC(20, 6) NOT NULL, 
	non_taxable_income NUMERIC(20, 6) NOT NULL, 
	rate_differential_on_foreign_income NUMERIC(20, 6) NOT NULL, 
	tax_credits_utilized NUMERIC(20, 6) NOT NULL, 
	change_in_unrecognized_dta NUMERIC(20, 6) NOT NULL, 
	effect_of_tax_rate_change NUMERIC(20, 6) NOT NULL, 
	prior_year_adjustments NUMERIC(20, 6) NOT NULL, 
	other_reconciling_items NUMERIC(20, 6) NOT NULL, 
	other_items_description TEXT, 
	total_tax_expense NUMERIC(20, 6) NOT NULL, 
	current_tax_expense NUMERIC(20, 6) NOT NULL, 
	deferred_tax_expense NUMERIC(20, 6) NOT NULL, 
	effective_tax_rate NUMERIC(10, 6) NOT NULL, 
	rate_variance NUMERIC(10, 6) NOT NULL, 
	notes TEXT, 
	prepared_by_user_id UUID NOT NULL, 
	reviewed_by_user_id UUID, 
	reviewed_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (reconciliation_id), 
	CONSTRAINT uq_tax_reconciliation UNIQUE (organization_id, fiscal_period_id, jurisdiction_id), 
	FOREIGN KEY(organization_id) REFERENCES core_org.organization (organization_id), 
	FOREIGN KEY(fiscal_period_id) REFERENCES gl.fiscal_period (fiscal_period_id), 
	FOREIGN KEY(jurisdiction_id) REFERENCES tax.tax_jurisdiction (jurisdiction_id)
);""",
        """CREATE TABLE IF NOT EXISTS tax.deferred_tax_movement (
	movement_id UUID DEFAULT gen_random_uuid() NOT NULL, 
	basis_id UUID NOT NULL, 
	fiscal_period_id UUID NOT NULL, 
	accounting_base_opening NUMERIC(20, 6) NOT NULL, 
	tax_base_opening NUMERIC(20, 6) NOT NULL, 
	temporary_difference_opening NUMERIC(20, 6) NOT NULL, 
	deferred_tax_opening NUMERIC(20, 6) NOT NULL, 
	accounting_base_movement NUMERIC(20, 6) NOT NULL, 
	tax_base_movement NUMERIC(20, 6) NOT NULL, 
	temporary_difference_movement NUMERIC(20, 6) NOT NULL, 
	tax_rate_opening NUMERIC(10, 6) NOT NULL, 
	tax_rate_closing NUMERIC(10, 6) NOT NULL, 
	tax_rate_change_impact NUMERIC(20, 6) NOT NULL, 
	deferred_tax_movement_pl NUMERIC(20, 6) NOT NULL, 
	deferred_tax_movement_oci NUMERIC(20, 6) NOT NULL, 
	deferred_tax_movement_equity NUMERIC(20, 6) NOT NULL, 
	accounting_base_closing NUMERIC(20, 6) NOT NULL, 
	tax_base_closing NUMERIC(20, 6) NOT NULL, 
	temporary_difference_closing NUMERIC(20, 6) NOT NULL, 
	deferred_tax_closing NUMERIC(20, 6) NOT NULL, 
	recognition_change NUMERIC(20, 6) NOT NULL, 
	unrecognized_closing NUMERIC(20, 6) NOT NULL, 
	movement_description TEXT, 
	movement_category VARCHAR(50) NOT NULL, 
	journal_entry_id UUID, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (movement_id), 
	FOREIGN KEY(basis_id) REFERENCES tax.deferred_tax_basis (basis_id), 
	FOREIGN KEY(fiscal_period_id) REFERENCES gl.fiscal_period (fiscal_period_id)
);""",
        """CREATE TABLE IF NOT EXISTS tax.tax_return (
	return_id UUID DEFAULT gen_random_uuid() NOT NULL, 
	organization_id UUID NOT NULL, 
	tax_period_id UUID NOT NULL, 
	jurisdiction_id UUID NOT NULL, 
	return_type tax_return_type NOT NULL, 
	return_reference VARCHAR(50), 
	total_output_tax NUMERIC(20, 6) NOT NULL, 
	total_input_tax NUMERIC(20, 6) NOT NULL, 
	net_tax_payable NUMERIC(20, 6) NOT NULL, 
	adjustments NUMERIC(20, 6) NOT NULL, 
	final_amount NUMERIC(20, 6) NOT NULL, 
	box_values JSONB, 
	status tax_return_status NOT NULL, 
	filed_date DATE, 
	filed_by_user_id UUID, 
	filing_reference VARCHAR(100), 
	is_paid BOOLEAN NOT NULL, 
	payment_date DATE, 
	payment_reference VARCHAR(100), 
	payment_journal_entry_id UUID, 
	is_amendment BOOLEAN NOT NULL, 
	original_return_id UUID, 
	amendment_reason VARCHAR(500), 
	prepared_by_user_id UUID, 
	prepared_at TIMESTAMP WITH TIME ZONE, 
	reviewed_by_user_id UUID, 
	reviewed_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (return_id), 
	FOREIGN KEY(organization_id) REFERENCES core_org.organization (organization_id), 
	FOREIGN KEY(tax_period_id) REFERENCES tax.tax_period (period_id), 
	FOREIGN KEY(jurisdiction_id) REFERENCES tax.tax_jurisdiction (jurisdiction_id)
);""",
        """CREATE INDEX IF NOT EXISTS idx_tax_return_period ON tax.tax_return (tax_period_id);""",
        """CREATE TABLE IF NOT EXISTS tax.tax_transaction (
	transaction_id UUID DEFAULT gen_random_uuid() NOT NULL, 
	organization_id UUID NOT NULL, 
	fiscal_period_id UUID NOT NULL, 
	tax_code_id UUID NOT NULL, 
	jurisdiction_id UUID NOT NULL, 
	transaction_type tax_transaction_type NOT NULL, 
	transaction_date DATE NOT NULL, 
	source_document_type VARCHAR(30) NOT NULL, 
	source_document_id UUID NOT NULL, 
	source_document_line_id UUID, 
	source_document_reference VARCHAR(100), 
	counterparty_type VARCHAR(30), 
	counterparty_id UUID, 
	counterparty_name VARCHAR(200), 
	counterparty_tax_id VARCHAR(50), 
	currency_code VARCHAR(3) NOT NULL, 
	base_amount NUMERIC(20, 6) NOT NULL, 
	tax_rate NUMERIC(10, 6) NOT NULL, 
	tax_amount NUMERIC(20, 6) NOT NULL, 
	exchange_rate NUMERIC(20, 10), 
	functional_base_amount NUMERIC(20, 6) NOT NULL, 
	functional_tax_amount NUMERIC(20, 6) NOT NULL, 
	recoverable_amount NUMERIC(20, 6) NOT NULL, 
	non_recoverable_amount NUMERIC(20, 6) NOT NULL, 
	tax_return_period VARCHAR(20), 
	tax_return_box VARCHAR(30), 
	is_included_in_return BOOLEAN NOT NULL, 
	journal_entry_id UUID, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (transaction_id), 
	FOREIGN KEY(fiscal_period_id) REFERENCES gl.fiscal_period (fiscal_period_id), 
	FOREIGN KEY(tax_code_id) REFERENCES tax.tax_code (tax_code_id), 
	FOREIGN KEY(jurisdiction_id) REFERENCES tax.tax_jurisdiction (jurisdiction_id)
);""",
        """CREATE INDEX IF NOT EXISTS idx_tax_txn_code ON tax.tax_transaction (tax_code_id);""",
        """CREATE INDEX IF NOT EXISTS idx_tax_txn_date ON tax.tax_transaction (transaction_date);""",
    ]
    for statement in statements:
        op.execute(statement)


def downgrade() -> None:
    statements = [
        """DROP TABLE IF EXISTS tax.tax_transaction CASCADE;""",
        """DROP TABLE IF EXISTS tax.tax_return CASCADE;""",
        """DROP TABLE IF EXISTS tax.deferred_tax_movement CASCADE;""",
        """DROP TABLE IF EXISTS tax.tax_reconciliation CASCADE;""",
        """DROP TABLE IF EXISTS tax.tax_period CASCADE;""",
        """DROP TABLE IF EXISTS tax.tax_code CASCADE;""",
        """DROP TABLE IF EXISTS tax.deferred_tax_basis CASCADE;""",
        """DROP TABLE IF EXISTS tax.tax_jurisdiction CASCADE;""",
        """DROP TYPE IF EXISTS tax_type CASCADE;""",
        """DROP TYPE IF EXISTS tax_transaction_type CASCADE;""",
        """DROP TYPE IF EXISTS tax_return_type CASCADE;""",
        """DROP TYPE IF EXISTS tax_return_status CASCADE;""",
        """DROP TYPE IF EXISTS tax_period_status CASCADE;""",
        """DROP TYPE IF EXISTS tax_period_frequency CASCADE;""",
        """DROP TYPE IF EXISTS difference_type CASCADE;""",
        """DROP SCHEMA IF EXISTS tax CASCADE;""",
    ]
    for statement in statements:
        op.execute(statement)
