"""The half of the authority proof that a `trust` cluster cannot produce.

`system_user` returns NULL under `trust` authentication. ERP's ordinary
integration lane is `POSTGRES_HOST_AUTH_METHOD: trust`, so it can exercise the
`session_user`/`current_user` half of the direct authentication proof and
nothing more. Binding an approved authentication METHOD and IDENTITY is only
meaningful against a cluster that really authenticates, which is why this
directory exists and why the `migration-authentication-proof` CI job runs
PostgreSQL with `scram-sha-256`.

## These tests FAIL rather than skip on a trust cluster

A skip is how this check would quietly stop running: the job would stay green
while proving nothing. `test_the_cluster_really_authenticates` asserts the
premise up front, so pointing this directory at a trust cluster reports a
failure naming exactly that.

## Deselected by the ordinary integration lane, never skipped

The lane that runs against the trust cluster passes `-m "not authentication"`,
so these are DESELECTED there rather than skipped inside — a skip is a result
this file reports, and it must never report a result about a cluster that
authenticated nothing.

It lives under `tests/integration/` rather than in a directory of its own so
that it inherits `tests/integration/conftest.py`, which undoes the SQLite type
monkey-patching `tests/conftest.py` applies to the whole `tests` package. A
separate directory would have needed a second copy of that un-patching, and two
copies of it is a defect waiting for the next PostgreSQL type.

`tests/architecture/test_migration_authority_callers.py` pins the pairing: the
deselection and the job that selects the marker must both exist, and the job
must not be a trust cluster.

## Credentials

The passwords here are generated by the workflow for one disposable
PostgreSQL container and exist nowhere else. Production credentials are never
read, minted or rotated by any test.
"""

from __future__ import annotations

import os
import subprocess
import sys
from collections.abc import Iterator

import psycopg
import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy import URL, make_url
from sqlalchemy.dialects import postgresql
from sqlalchemy.engine import Engine

from app.migration_authority import (
    AUTHORITY_SUBJECTS,
    EXPECTED_AUTHENTICATION_VAR,
    MIGRATION_AUTHENTICATION_IDENTITY_MISMATCH,
    ROLE_AUTHORITY_SQL,
    observation_from_rows,
)
from app.migration_database_roles import MIGRATION_EXECUTOR

pytestmark = [pytest.mark.integration, pytest.mark.authentication]

EXPECTED_METHOD = "scram-sha-256"


@pytest.fixture(autouse=True)
def real_postgresql_types(engine: Engine) -> None:
    """Undo `tests/conftest.py`'s SQLite type patch before any migration runs.

    `tests/conftest.py` replaces `sqlalchemy.dialects.postgresql.UUID` with a
    `String(36)` TypeDecorator so the SQLite unit suite can import the models.
    `tests/integration/conftest.py` undoes that — but only inside the
    session-scoped `engine` fixture. A module that never asks for `engine`
    therefore runs `alembic upgrade` with UUID columns rendering as VARCHAR, and
    the chain dies on a real foreign key: `people.organization_id` cannot
    reference `core_org.organization(organization_id)` when one is `varchar` and
    the other is `uuid`.

    Every other PostgreSQL module in this directory gets the restoration BY
    ACCIDENT, because some alphabetically earlier module happened to ask for
    `engine` first. Depending on that is depending on collection order. This
    fixture makes the dependency explicit, and the assertion below means it
    cannot silently stop working: if someone removes the parameter, the patched
    class is detected here rather than eight migrations later as a type
    mismatch nobody connects to a test fixture.
    """
    assert postgresql.UUID.__module__.startswith("sqlalchemy"), (
        "postgresql.UUID is still the SQLite-compatible stand-in from "
        "tests/conftest.py; every UUID column this migration chain creates "
        "would be VARCHAR"
    )


def _migration_url() -> URL:
    configured = os.getenv("MIGRATION_DATABASE_URL")
    if not configured:
        raise pytest.UsageError(
            "the authentication proof requires MIGRATION_DATABASE_URL for the "
            "password-authenticated app_admin"
        )
    return make_url(configured)


def _psycopg_url(url: URL) -> str:
    return url.set(drivername="postgresql").render_as_string(hide_password=False)


def _observation():
    with psycopg.connect(_psycopg_url(_migration_url()), autocommit=True) as connection:
        rows = connection.execute(
            ROLE_AUTHORITY_SQL, {"subjects": sorted(AUTHORITY_SUBJECTS)}
        ).fetchall()
    return observation_from_rows(rows)


@pytest.fixture()
def bound(monkeypatch: pytest.MonkeyPatch) -> Iterator[None]:
    monkeypatch.setenv(
        EXPECTED_AUTHENTICATION_VAR, f"{EXPECTED_METHOD}:{MIGRATION_EXECUTOR}"
    )
    yield


def _config() -> Config:
    config = Config("alembic.ini")
    config.set_main_option("script_location", "alembic")
    config.set_main_option(
        "sqlalchemy.url", _migration_url().render_as_string(hide_password=False)
    )
    return config


def test_the_cluster_really_authenticates() -> None:
    """The PREMISE, asserted before anything is derived from it.

    On a `trust` cluster `system_user` is NULL and every assertion below would
    be about a cluster that never checked a password. This fails there, loudly,
    instead of skipping.
    """
    observation = _observation()
    assert observation.system_user is not None, (
        "system_user is NULL, which is what PostgreSQL returns under trust "
        "authentication. This tier is supposed to be the one that really "
        "authenticates; a trust cluster cannot be authentication evidence"
    )
    assert observation.system_user == f"{EXPECTED_METHOD}:{MIGRATION_EXECUTOR}"
    assert observation.session_user == observation.current_user == MIGRATION_EXECUTOR


def test_a_bound_migration_upgrades(bound: None) -> None:
    """The near-miss. Without it, a policy that refused every bound
    expectation would satisfy both refusals below."""
    command.upgrade(_config(), "heads")


@pytest.mark.parametrize(
    "expectation",
    ["md5:app_admin", "scram-sha-256:someone_else", "cert:app_admin"],
)
def test_a_wrong_authentication_binding_refuses(
    expectation: str, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Method and identity are asserted separately, and both must hold.

    A cluster reconfigured to a weaker method, or a role renamed into the
    executor's place, are different failures with the same consequence: the
    connection is not the one that was authorised.
    """
    monkeypatch.setenv(EXPECTED_AUTHENTICATION_VAR, expectation)
    with pytest.raises(RuntimeError) as raised:
        command.upgrade(_config(), "heads")
    message = str(raised.value)
    assert MIGRATION_AUTHENTICATION_IDENTITY_MISMATCH in message
    assert expectation in message


def test_an_unbound_run_reports_unverified_rather_than_passing_silently(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    """Absent is REPORTED, never assumed — the same shape as the database
    identity binding. An operator who has not adopted it is not blocked, and
    cannot read a green run as a checked one."""
    monkeypatch.delenv(EXPECTED_AUTHENTICATION_VAR, raising=False)
    command.upgrade(_config(), "heads")
    assert "authentication UNVERIFIED" in capsys.readouterr().err


def test_the_deploy_preflight_makes_the_same_assertion(bound: None) -> None:
    """`--verify-only` is `scripts/deploy.sh` step 3a and must not be weaker
    than the migration it gates."""
    satisfied = subprocess.run(  # noqa: S603
        [sys.executable, "scripts/bootstrap_database_roles.py", "--verify-only"],
        env=dict(os.environ),
        capture_output=True,
        text=True,
        check=False,
    )
    assert satisfied.returncode == 0, satisfied.stderr

    wrong = dict(os.environ)
    wrong[EXPECTED_AUTHENTICATION_VAR] = "md5:app_admin"
    refused = subprocess.run(  # noqa: S603
        [sys.executable, "scripts/bootstrap_database_roles.py", "--verify-only"],
        env=wrong,
        capture_output=True,
        text=True,
        check=False,
    )
    assert refused.returncode == 1
    assert MIGRATION_AUTHENTICATION_IDENTITY_MISMATCH in refused.stderr
