"""
People (HR/HRIS) Pydantic Schemas.

This module contains all Pydantic schemas for the People/HR API endpoints.

Schema naming convention:
- {Entity}Base: Common fields for create/update
- {Entity}Create: Fields for creating a new record
- {Entity}Update: Fields for updating an existing record
- {Entity}Read: Fields returned from API (includes id, timestamps)
- {Entity}Brief: Minimal fields for list views / dropdowns
"""

# HR Core Schemas
from .hr import (
    # Department
    DepartmentBase,
    DepartmentCreate,
    DepartmentUpdate,
    DepartmentRead,
    DepartmentListResponse,
    # Designation
    DesignationBase,
    DesignationCreate,
    DesignationUpdate,
    DesignationRead,
    # Employment Type
    EmploymentTypeBase,
    EmploymentTypeCreate,
    EmploymentTypeUpdate,
    EmploymentTypeRead,
    # Employee Grade
    EmployeeGradeBase,
    EmployeeGradeCreate,
    EmployeeGradeUpdate,
    EmployeeGradeRead,
    # Employee
    EmployeeBase,
    EmployeeCreate,
    EmployeeUpdate,
    EmployeeRead,
    EmployeeListResponse,
    EmployeeSummaryRead,
    LocationBase,
    LocationCreate,
    LocationUpdate,
    LocationRead,
    LocationListResponse,
)

# Payroll Schemas
from .payroll import (
    SalaryComponentBase,
    SalaryComponentCreate,
    SalaryComponentUpdate,
    SalaryComponentRead,
    SalaryStructureBase,
    SalaryStructureCreate,
    SalaryStructureUpdate,
    SalaryStructureRead,
    SalarySlipRead,
    PayrollEntryBase,
    PayrollEntryCreate,
    PayrollEntryRead,
)

# Leave Schemas
from .leave import (
    LeaveTypeBase,
    LeaveTypeCreate,
    LeaveTypeUpdate,
    LeaveTypeRead,
    LeaveTypeListResponse,
    HolidayListBase,
    HolidayListCreate,
    HolidayListUpdate,
    HolidayListRead,
    HolidayBase,
    HolidayCreate,
    HolidayRead,
    LeaveAllocationBase,
    LeaveAllocationCreate,
    LeaveAllocationUpdate,
    LeaveAllocationRead,
    LeaveAllocationListResponse,
    LeaveBalanceSummary,
    LeaveApplicationBase,
    LeaveApplicationCreate,
    LeaveApplicationUpdate,
    LeaveApplicationRead,
    LeaveApplicationListResponse,
    LeaveApprovalRequest,
    LeaveStats,
)

# Attendance Schemas
from .attendance import (
    ShiftTypeBase,
    ShiftTypeCreate,
    ShiftTypeUpdate,
    ShiftTypeRead,
    ShiftTypeListResponse,
    AttendanceBase,
    AttendanceCreate,
    AttendanceUpdate,
    AttendanceRead,
    AttendanceListResponse,
    BulkAttendanceCreate,
    CheckInRequest,
    CheckOutRequest,
    AttendanceSummary,
    DailyAttendanceSummary,
)

# Lifecycle Schemas
from .lifecycle import (
    OnboardingCreate,
    OnboardingRead,
    OnboardingUpdate,
    OnboardingListResponse,
    SeparationCreate,
    SeparationRead,
    SeparationUpdate,
    SeparationListResponse,
    PromotionCreate,
    PromotionRead,
    PromotionUpdate,
    PromotionListResponse,
    TransferCreate,
    TransferRead,
    TransferUpdate,
    TransferListResponse,
)

# Recruitment Schemas
from .recruit import (
    JobOpeningBase,
    JobOpeningCreate,
    JobOpeningUpdate,
    JobOpeningRead,
    JobOpeningListResponse,
    JobOpeningStats,
    JobApplicantBase,
    JobApplicantCreate,
    JobApplicantUpdate,
    JobApplicantRead,
    JobApplicantListResponse,
    ApplicantStatusUpdateRequest,
    ApplicantStats,
    InterviewBase,
    InterviewCreate,
    InterviewUpdate,
    InterviewRead,
    InterviewListResponse,
    InterviewFeedbackRequest,
    InterviewRescheduleRequest,
    JobOfferBase,
    JobOfferCreate,
    JobOfferUpdate,
    JobOfferRead,
    JobOfferListResponse,
    OfferApprovalRequest,
    OfferExtendRequest,
    OfferResponseRequest,
    OfferConvertRequest,
    RecruitmentStats,
)

# Asset Assignment Schemas
from .assets import (
    AssetAssignmentCreate,
    AssetAssignmentReturnRequest,
    AssetAssignmentTransferRequest,
    AssetAssignmentRead,
    AssetAssignmentListResponse,
)

# Checklist Schemas
from .checklist import (
    ChecklistTemplateCreate,
    ChecklistTemplateUpdate,
    ChecklistTemplateRead,
    ChecklistTemplateListResponse,
    ChecklistItemCreate,
    ChecklistItemRead,
)

# Training Schemas
from .training import (
    TrainingProgramBase,
    TrainingProgramCreate,
    TrainingProgramUpdate,
    TrainingProgramRead,
    TrainingProgramListResponse,
    TrainingEventBase,
    TrainingEventCreate,
    TrainingEventUpdate,
    TrainingEventRead,
    TrainingEventListResponse,
    TrainingAttendeeBase,
    TrainingAttendeeCreate,
    TrainingAttendeeUpdate,
    TrainingAttendeeRead,
    TrainingAttendeeListResponse,
    BulkInviteRequest,
    AttendeeFeedbackRequest,
    IssueCertificateRequest,
    TrainingStats,
    EmployeeTrainingHistory,
)

# Performance Schemas
from .perf import (
    AppraisalCycleBase,
    AppraisalCycleCreate,
    AppraisalCycleUpdate,
    AppraisalCycleRead,
    AppraisalCycleListResponse,
    KRABase,
    KRACreate,
    KRAUpdate,
    KRARead,
    KRAListResponse,
    KPIBase,
    KPICreate,
    KPIUpdate,
    KPIRead,
    KPIListResponse,
    KPIProgressUpdateRequest,
    AppraisalBase,
    AppraisalCreate,
    AppraisalUpdate,
    AppraisalRead,
    AppraisalListResponse,
    SelfAssessmentRequest,
    ManagerReviewRequest,
    CalibrationRequest,
    FeedbackSubmitRequest,
    ScorecardBase,
    ScorecardCreate,
    ScorecardUpdate,
    ScorecardRead,
    ScorecardListResponse,
    FinalizeScorecardRequest,
    PerformanceStats,
    PerformanceTrend,
)

# Expense Schemas
from .expense import (
    ExpenseCategoryBase,
    ExpenseCategoryCreate,
    ExpenseCategoryUpdate,
    ExpenseCategoryRead,
    ExpenseCategoryListResponse,
    ExpenseClaimItemBase,
    ExpenseClaimItemCreate,
    ExpenseClaimItemRead,
    ExpenseClaimBase,
    ExpenseClaimCreate,
    ExpenseClaimUpdate,
    ExpenseClaimRead,
    ExpenseClaimListResponse,
    ExpenseClaimApprovalRequest,
    LinkAdvanceRequest,
    CashAdvanceBase,
    CashAdvanceCreate,
    CashAdvanceUpdate,
    CashAdvanceRead,
    CashAdvanceListResponse,
    CashAdvanceApprovalRequest,
    CashAdvanceDisburseRequest,
    CashAdvanceRefundRequest,
    CorporateCardBase,
    CorporateCardCreate,
    CorporateCardUpdate,
    CorporateCardRead,
    CorporateCardListResponse,
    DeactivateCardRequest,
    CardTransactionBase,
    CardTransactionCreate,
    CardTransactionUpdate,
    CardTransactionRead,
    CardTransactionListResponse,
    MatchTransactionRequest,
    MarkPersonalRequest,
    ExpenseStats,
    EmployeeExpenseSummary,
)

__all__ = [
    # HR Core
    "DepartmentBase",
    "DepartmentCreate",
    "DepartmentUpdate",
    "DepartmentRead",
    "DepartmentListResponse",
    "DesignationBase",
    "DesignationCreate",
    "DesignationUpdate",
    "DesignationRead",
    "EmploymentTypeBase",
    "EmploymentTypeCreate",
    "EmploymentTypeUpdate",
    "EmploymentTypeRead",
    "EmployeeGradeBase",
    "EmployeeGradeCreate",
    "EmployeeGradeUpdate",
    "EmployeeGradeRead",
    "EmployeeBase",
    "EmployeeCreate",
    "EmployeeUpdate",
    "EmployeeRead",
    "EmployeeListResponse",
    "EmployeeSummaryRead",
    "LocationBase",
    "LocationCreate",
    "LocationUpdate",
    "LocationRead",
    "LocationListResponse",
    # Payroll
    "SalaryComponentBase",
    "SalaryComponentCreate",
    "SalaryComponentUpdate",
    "SalaryComponentRead",
    "SalaryStructureBase",
    "SalaryStructureCreate",
    "SalaryStructureUpdate",
    "SalaryStructureRead",
    "SalarySlipRead",
    "PayrollEntryBase",
    "PayrollEntryCreate",
    "PayrollEntryRead",
    # Leave
    "LeaveTypeBase",
    "LeaveTypeCreate",
    "LeaveTypeUpdate",
    "LeaveTypeRead",
    "LeaveTypeListResponse",
    "HolidayListBase",
    "HolidayListCreate",
    "HolidayListUpdate",
    "HolidayListRead",
    "HolidayBase",
    "HolidayCreate",
    "HolidayRead",
    "LeaveAllocationBase",
    "LeaveAllocationCreate",
    "LeaveAllocationUpdate",
    "LeaveAllocationRead",
    "LeaveAllocationListResponse",
    "LeaveBalanceSummary",
    "LeaveApplicationBase",
    "LeaveApplicationCreate",
    "LeaveApplicationUpdate",
    "LeaveApplicationRead",
    "LeaveApplicationListResponse",
    "LeaveApprovalRequest",
    "LeaveStats",
    # Attendance
    "ShiftTypeBase",
    "ShiftTypeCreate",
    "ShiftTypeUpdate",
    "ShiftTypeRead",
    "ShiftTypeListResponse",
    "AttendanceBase",
    "AttendanceCreate",
    "AttendanceUpdate",
    "AttendanceRead",
    "AttendanceListResponse",
    "BulkAttendanceCreate",
    "CheckInRequest",
    "CheckOutRequest",
    "AttendanceSummary",
    "DailyAttendanceSummary",
    # Recruitment
    "JobOpeningBase",
    "JobOpeningCreate",
    "JobOpeningUpdate",
    "JobOpeningRead",
    "JobOpeningListResponse",
    "JobOpeningStats",
    "JobApplicantBase",
    "JobApplicantCreate",
    "JobApplicantUpdate",
    "JobApplicantRead",
    "JobApplicantListResponse",
    "ApplicantStatusUpdateRequest",
    "ApplicantStats",
    "InterviewBase",
    "InterviewCreate",
    "InterviewUpdate",
    "InterviewRead",
    "InterviewListResponse",
    "InterviewFeedbackRequest",
    "InterviewRescheduleRequest",
    "JobOfferBase",
    "JobOfferCreate",
    "JobOfferUpdate",
    "JobOfferRead",
    "JobOfferListResponse",
    "OfferApprovalRequest",
    "OfferExtendRequest",
    "OfferResponseRequest",
    "OfferConvertRequest",
    "RecruitmentStats",
    # Assets
    "AssetAssignmentCreate",
    "AssetAssignmentReturnRequest",
    "AssetAssignmentTransferRequest",
    "AssetAssignmentRead",
    "AssetAssignmentListResponse",
    # Checklist
    "ChecklistTemplateCreate",
    "ChecklistTemplateUpdate",
    "ChecklistTemplateRead",
    "ChecklistTemplateListResponse",
    "ChecklistItemCreate",
    "ChecklistItemRead",
    # Training
    "TrainingProgramBase",
    "TrainingProgramCreate",
    "TrainingProgramUpdate",
    "TrainingProgramRead",
    "TrainingProgramListResponse",
    "TrainingEventBase",
    "TrainingEventCreate",
    "TrainingEventUpdate",
    "TrainingEventRead",
    "TrainingEventListResponse",
    "TrainingAttendeeBase",
    "TrainingAttendeeCreate",
    "TrainingAttendeeUpdate",
    "TrainingAttendeeRead",
    "TrainingAttendeeListResponse",
    "BulkInviteRequest",
    "AttendeeFeedbackRequest",
    "IssueCertificateRequest",
    "TrainingStats",
    "EmployeeTrainingHistory",
    # Performance
    "AppraisalCycleBase",
    "AppraisalCycleCreate",
    "AppraisalCycleUpdate",
    "AppraisalCycleRead",
    "AppraisalCycleListResponse",
    "KRABase",
    "KRACreate",
    "KRAUpdate",
    "KRARead",
    "KRAListResponse",
    "KPIBase",
    "KPICreate",
    "KPIUpdate",
    "KPIRead",
    "KPIListResponse",
    "KPIProgressUpdateRequest",
    "AppraisalBase",
    "AppraisalCreate",
    "AppraisalUpdate",
    "AppraisalRead",
    "AppraisalListResponse",
    "SelfAssessmentRequest",
    "ManagerReviewRequest",
    "CalibrationRequest",
    "FeedbackSubmitRequest",
    "ScorecardBase",
    "ScorecardCreate",
    "ScorecardUpdate",
    "ScorecardRead",
    "ScorecardListResponse",
    "FinalizeScorecardRequest",
    "PerformanceStats",
    "PerformanceTrend",
    # Expense
    "ExpenseCategoryBase",
    "ExpenseCategoryCreate",
    "ExpenseCategoryUpdate",
    "ExpenseCategoryRead",
    "ExpenseCategoryListResponse",
    "ExpenseClaimItemBase",
    "ExpenseClaimItemCreate",
    "ExpenseClaimItemRead",
    "ExpenseClaimBase",
    "ExpenseClaimCreate",
    "ExpenseClaimUpdate",
    "ExpenseClaimRead",
    "ExpenseClaimListResponse",
    "ExpenseClaimApprovalRequest",
    "LinkAdvanceRequest",
    "CashAdvanceBase",
    "CashAdvanceCreate",
    "CashAdvanceUpdate",
    "CashAdvanceRead",
    "CashAdvanceListResponse",
    "CashAdvanceApprovalRequest",
    "CashAdvanceDisburseRequest",
    "CashAdvanceRefundRequest",
    "CorporateCardBase",
    "CorporateCardCreate",
    "CorporateCardUpdate",
    "CorporateCardRead",
    "CorporateCardListResponse",
    "DeactivateCardRequest",
    "CardTransactionBase",
    "CardTransactionCreate",
    "CardTransactionUpdate",
    "CardTransactionRead",
    "CardTransactionListResponse",
    "MatchTransactionRequest",
    "MarkPersonalRequest",
    "ExpenseStats",
    "EmployeeExpenseSummary",
]
