"""
Coach Insight model.

Stores precomputed, role-scoped coaching insights generated by analyzers/LLMs.
"""

from __future__ import annotations

import enum
import uuid
from datetime import UTC, date, datetime

from sqlalchemy import JSON, Date, DateTime, Float, Index, String, Text, func, text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db import Base

_JSON = JSON().with_variant(JSONB, "postgresql")


class InsightCategory(str, enum.Enum):
    CASH_FLOW = "CASH_FLOW"
    EFFICIENCY = "EFFICIENCY"
    WORKFORCE = "WORKFORCE"
    SUPPLY_CHAIN = "SUPPLY_CHAIN"
    ASSETS = "ASSETS"
    REVENUE = "REVENUE"
    COMPLIANCE = "COMPLIANCE"
    DATA_QUALITY = "DATA_QUALITY"


class InsightSeverity(str, enum.Enum):
    INFO = "INFO"
    ATTENTION = "ATTENTION"
    WARNING = "WARNING"
    URGENT = "URGENT"


class InsightAudience(str, enum.Enum):
    EMPLOYEE = "EMPLOYEE"
    MANAGER = "MANAGER"
    HR = "HR"
    FINANCE = "FINANCE"
    OPERATIONS = "OPERATIONS"
    EXECUTIVE = "EXECUTIVE"


class InsightStatus(str, enum.Enum):
    GENERATED = "GENERATED"
    DELIVERED = "DELIVERED"
    READ = "READ"
    ACTED_ON = "ACTED_ON"
    DISMISSED = "DISMISSED"


class CoachInsight(Base):
    """A single coaching insight (typically precomputed via Celery)."""

    __tablename__ = "coach_insight"
    __table_args__ = (
        Index("idx_coach_insight_org", "organization_id"),
        Index("idx_coach_insight_org_status", "organization_id", "status"),
        Index("idx_coach_insight_org_target", "organization_id", "target_employee_id"),
        Index("idx_coach_insight_valid_until", "valid_until"),
    )

    insight_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
    )
    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False
    )

    # Target
    audience: Mapped[str] = mapped_column(String(30), nullable=False)
    target_employee_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), nullable=True
    )

    # Classification
    category: Mapped[str] = mapped_column(String(30), nullable=False)
    severity: Mapped[str] = mapped_column(String(20), nullable=False)

    # Content
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    detail: Mapped[str | None] = mapped_column(Text, nullable=True)
    coaching_action: Mapped[str] = mapped_column(Text, nullable=False)

    # Evidence
    confidence: Mapped[float] = mapped_column(Float, nullable=False, default=0.5)
    data_sources: Mapped[dict] = mapped_column(_JSON, nullable=False, default=dict)
    evidence: Mapped[dict] = mapped_column(_JSON, nullable=False, default=dict)

    # Lifecycle
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="GENERATED")
    delivered_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    read_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    dismissed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    feedback: Mapped[str | None] = mapped_column(String(30), nullable=True)

    # TTL
    valid_until: Mapped[date] = mapped_column(Date, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(UTC),
        server_default=func.now(),
    )
